import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { BlackButton } from './global-components'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function Navbar() {
  return (
    <nav className='h-18 inset-x-0 top-0 bg-cupcake-dark-grey sticky'>
      <div className='flex justify-between items-center w-36'>
        <BlackButton item={{ link: '/', text: 'Home' }} />
        <BlackButton item={{ link: '/recipies', text: 'Recepies' }} />
      </div>
    </nav>
  )
}
function Footer() {
  return (
    <footer className='inset-x-0 bottom-0 h-18 bg-cupcake-dark-grey'><h2 className='text-lg py-2'>Footer</h2>
    </footer>
  )
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className='my-20 mx-14 min-h-screen'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
