import "./globals.css";
import type { Metadata } from "next";
import { Inter, VT323 } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const vt323 = VT323({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Navbar() {
  return (
    <nav className="h-18 inset-x-0 top-0 bg-cupcake-dark-grey sticky">
      <h1 className="text-lg py-2">Navbar</h1>
    </nav>
  );
}
function Footer() {
  return (
    <footer className="inset-x-0 bottom-0 h-18 bg-cupcake-dark-grey">
      <h2 className="text-lg py-2">Footer</h2>
    </footer>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={vt323.className}>
        <Navbar />
        <main className="my-20 mx-14 min-h-screen">{children}</main>
        <Footer />
        <script src="https://unpkg.com/flowbite@1.5.1/dist/flowbite.js"></script>
      </body>
    </html>
  );
}
